management:
  endpoints:
    metrics:
      enabled: true
    web:
      exposure:
        include: info,health,metrics

  metrics:
    export:
      elastic:
        enabled: true
        step: 1m
        index: metrics
        autoCreateIndex: false

logging:
  level:
    org.apache.http: DEBUG
    io.micrometer.elastic: DEBUG

spring:
  http:
    log-request-details: true