management:
  metrics:

    export:
      elastic:
        enabled: false
      prometheus:
        enabled: false
        rsocket:
          enabled: false

    tags:
      app: metrics-demo
      env: dev
