---
version: "3"
services:

  kibana:
    image: kibana:7.2.0
    container_name: metrics-kibana
    ports:
    - "5601:5601"

  elasticsearch:
    image: elasticsearch:7.2.0
    container_name: metrics-elastic
    environment:
      discovery.type: single-node
    ports:
      - "9200:9200"
      - "9300:9300"
