{
 "title": "Hystrix Dashboard",
 "description": "Dashboard to monitor key metrics for Hystrix. The Hystrix metrics are published using Prometheus' simpleclient through this library https://github.com/soundcloud/prometheus-hystrix",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "application",
    "label": "Application",
    "query": "label_values(hystrix_requests_total, application)"
   },
   {
    "name": "commandGroup",
    "label": "Command Group",
    "query": "label_values(hystrix_requests_total{application=\"$application\"}, group)"
   },
   {
    "name": "commandName",
    "label": "Command Name",
    "query": "label_values(hystrix_requests_total{application=\"$application\",group=\"$commandGroup\"}, key)"
   }
  ]
 },
 "panels": [
  {
   "title": "Overall Status",
   "type": "singlestat",
   "gridPos": { "h": 22, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "hystrix_circuit_breaker_open{application=\"$application\", group=\"$commandGroup\", key=\"$commandName\"}"
    }
   ]
  },
  {
   "title": "Requests / Minute",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 4, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(hystrix_requests_total{application=\"$application\", group=\"$commandGroup\", key=\"$commandName\"}[1m]) * 60",
     "legendFormat": "Requests / Min"
    }
   ]
  },
  {
   "title": "Average Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 0 },
   "yaxes": [
    { "format": "dtdurationms" }
   ],
   "targets": [
    {
     "expr": "rate(hystrix_latency_total_seconds_sum{application=\"$application\", group=\"$commandGroup\", key=\"$commandName\"}[1m]) / rate(hystrix_latency_total_seconds_count{application=\"$application\", group=\"$commandGroup\", key=\"$commandName\"}[1m]) * 60",
     "legendFormat": " Average Total Latency"
    },
    {
     "expr": "rate(hystrix_latency_execution_seconds_sum{application=\"$application\", group=\"$commandGroup\", key=\"$commandName\"}[1m]) / rate(hystrix_latency_execution_seconds_count{application=\"$application\", group=\"$commandGroup\", key=\"$commandName\"}[1m]) * 60",
     "legendFormat": " Average Execution Latency"
    }
   ]
  },
  {
   "title": "Execution Details / Minute",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 4, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(hystrix_execution_total{application=\"$application\", group=\"$commandGroup\", key=\"$commandName\"}[1m]) * 60",
     "legendFormat": "{{event}}"
    }
   ]
  },
  {
   "title": "Max Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "hystrix_latency_total_seconds_max{application=\"$application\", group=\"$commandGroup\", key=\"$commandName\"}",
     "legendFormat": "Max Total Latency"
    },
    {
     "expr": "hystrix_latency_execution_seconds_max{application=\"$application\", group=\"$commandGroup\", key=\"$commandName\"}",
     "legendFormat": "Max Execution Latency"
    }
   ]
  },
  {
   "title": "Command Details / Minute",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 4, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(hystrix_command_other_total{application=\"$application\", group=\"$commandGroup\", key=\"$commandName\"}[1m]) * 60",
     "legendFormat": "{{event}}"
    }
   ]
  },
  {
   "title": "Fallback Details / Minute",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(hystrix_fallback_total{application=\"$application\", group=\"$commandGroup\", key=\"$commandName\"}[1m]) * 60",
     "legendFormat": "{{event}}"
    }
   ]
  }
 ]
}